# Generated by Django 3.2.3 on 2021-05-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(blank=True, max_length=50, null=True)),
                ('warehouse_address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('product_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('product_reorder', models.IntegerField(blank=True, default='0', null=True)),
                ('product_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_items_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_price', models.IntegerField(blank=True, default='0', null=True)),
                ('selling_price', models.IntegerField(blank=True, default='0', null=True)),
                ('product_sold', models.BooleanField(default=0)),
                ('sold_to', models.CharField(blank=True, choices=[('Ebay', 'Ebay'), ('Flipkart', 'Flipkart'), ('Amazon', 'Amazon')], max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_in', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
                ('product_item_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('purchased_from', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.suppliers')),
            ],
        ),
    ]
