# Generated by Django 3.2.3 on 2021-05-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
        ),
        migrations.CreateModel(
            name='Product_items_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_items_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product_items')),
            ],
        ),
    ]
