# Generated by Django 3.2.3 on 2021-05-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210519_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_items_details',
            name='product_sold',
            field=models.BooleanField(default=False),
        ),
    ]
