# Generated by Django 3.2.3 on 2021-05-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210519_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_items_details',
            old_name='product_items_id',
            new_name='product_item_name',
        ),
    ]
