# Generated by Django 3.2.3 on 2021-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_product_items_id_product_items_details_product_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_items_details',
            name='sold_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
