# Generated by Django 3.2.3 on 2021-05-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_customers_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_items_details',
            name='purchased_from',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.suppliers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_items_details',
            name='sold_to',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.customers'),
            preserve_default=False,
        ),
    ]
