# Generated by Django 3.2.3 on 2021-05-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20210525_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_items_details',
            name='sold_to',
            field=models.CharField(blank=True, choices=[('Amazon', 'Amazon'), ('Flipkart', 'Flipkart'), ('Ebay', 'Ebay')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, default='0', null=True)),
                ('warehouse', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product_items_details')),
                ('rack', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.rack')),
            ],
        ),
    ]
