# Generated by Django 3.2.3 on 2021-05-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_items_product_items_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_items_details',
            name='purchased_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product_items_details',
            name='purchased_price',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
