# Generated by Django 3.2.3 on 2021-05-19 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210519_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_items_details',
            name='product_in',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
            preserve_default=False,
        ),
    ]
