# Generated by Django 3.2.3 on 2021-05-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210524_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_items_details',
            name='sold_to',
            field=models.CharField(blank=True, choices=[('Sk-electrics', 'Sk-electrics'), ('Electronic-city', 'Electronic-city'), ('China-traders', 'China-traders')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
