# Generated by Django 3.2.3 on 2021-05-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_product_items_details_sold_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='product_items_details',
            name='sold_to',
            field=models.CharField(blank=True, choices=[('Flipkart', 'Flipkart'), ('Amazon', 'Amazon'), ('Ebay', 'Ebay')], max_length=50, null=True),
        ),
    ]
