# Generated by Django 3.2.3 on 2021-05-30 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20210530_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_items_details',
            name='product_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='product_items_details',
            name='product_item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products'),
        ),
        migrations.AlterField(
            model_name='product_items_details',
            name='purchased_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.suppliers'),
        ),
        migrations.AlterField(
            model_name='product_items_details',
            name='sold_to',
            field=models.CharField(blank=True, choices=[('Flipkart', 'Flipkart'), ('Ebay', 'Ebay'), ('Amazon', 'Amazon')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Products_Sold',
        ),
    ]
