# Generated by Django 3.2.3 on 2021-07-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20210701_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_items_details',
            name='room',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.rack'),
            preserve_default=False,
        ),
    ]
