# Generated by Django 3.2.3 on 2021-07-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_product_items_details_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Rack',
        ),
    ]
