# Generated by Django 3.2.3 on 2021-07-05 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0024_delete_product_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='payment_due',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=19),
        ),
        migrations.AddField(
            model_name='customers',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='total_order_amount',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=19),
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customers',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product_items_details',
            name='sold_to',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.customers'),
            preserve_default=False,
        ),
    ]
