# Generated by Django 3.2.3 on 2021-07-07 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_product_items_details_sold_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='customer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productorder',
            name='order_cancelled',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='productorder',
            name='order_delivered',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='productorder',
            name='order_placed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='productorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
