# Generated by Django 3.2.3 on 2021-07-07 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20210707_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_items_details',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productorder'),
        ),
        migrations.AddField(
            model_name='product_items_details',
            name='reserved',
            field=models.BooleanField(default=0),
        ),
    ]
