# Generated by Django 3.2.3 on 2021-07-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_remove_productorder_order_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='order_paid',
            field=models.BooleanField(default=0),
        ),
    ]
