# Generated by Django 3.2.3 on 2021-07-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_employee_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
